#!/bin/bash
set -e

host="$1"
shift
cmd="$@"

until nc -z "$host" 9000; do
  >&2 echo "client-server unavailable - sleeping"
  sleep 1
done

>&2 echo "client-server is up - executing command"
exec $cmd