name: ligi-devprod
services:
  api:
    image: ligi-api-devprod
    build:
      dockerfile: ./config/server/Dockerfile
      context: .
      target: prod

  web:
    image: ligi-client-devprod
    build:
      dockerfile: ./config/client/Dockerfile
      context: .

  nginx:
    image: ligi-nginx-devprod
    depends_on:
      - api
      - web
    restart: always
    build:
      dockerfile: ./config/nginx/Dockerfile
      context: .
    ports:
      - "8100:8100"

networks:
  default:
    name: app-network
    driver: bridge
