version: '3'

services:
  ligiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: liginodejs
    container_name: ligiserver
    env_file: .env
    ports:
      - '7777:7777'
    volumes:
      - node_modules:/home/node/src/node_modules
volumes:
  node_modules:
