services:
  api:
    image: ligi-api-dev
    build:
      dockerfile: ./config/server/dev/Dockerfile
      context: .
    volumes:
      - ./backend/src:/app/src
    networks:
      - app-network
  db:
    image: mongo:7.0.22-jammy
    container_name: db
    restart: unless-stopped
    env_file: ./config/server/dev/server.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    healthcheck:
      # test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      test: echo 'db.runCommand("ping").ok'
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

#   client:
#     image: ligi-client-dev
#     depends_on:
#       - api
#     stdin_open: true
#     build:
#       dockerfile: ./config/client/dev/Dockerfile
#       context: .
#     ports:
#       - "8040:8040"
#     volumes:
#       - ./frontend/src:/app/src
#     networks:
#       - app-network

#   nginx:
#     image: ligi-nginx-dev
#     depends_on:
#       - api
#       - client
#     restart: always
#     build:
#       dockerfile: ./config/nginx/Dockerfile
#       context: .
#     ports:
#       - "8100:8100"
#     networks:
#       - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: bridge
