version: '3'

services:
  ligiserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: liginodejs
    container_name: ligiserver
    env_file: .env
    environment:
      - MONGO_HOSTNAME=ligidb
    ports:
      - '7080:8080'
    volumes:
      - ./backend/build:/home/node/src
      - ./frontend/build:/home/node/src/public
      - node_modules:/home/node/src/node_modules
    command: ./wait-for.sh ligidb:27017 --  node app/index.js
  ligidb:
    image: mongo:4.2-bionic
    container_name: ligidb
    env_file: .env
    ports:
      - '27070:27017'
    volumes:
      - ligidbdata:/data/db
volumes:
  ligidbdata:
  node_modules:
