version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: server
    env_file: .env
    environment:
      - MONGO_HOSTNAME=db
    ports:
      - '7080:8080'
    volumes:
      - ./backend/build:/home/node/src
      - ./frontend/build:/home/node/src/public
      - node_modules:/home/node/src/node_modules
    command: ./wait-for.sh db:27017 --  node app/index.js
  db:
    image: mongo:4.2-bionic
    container_name: db
    env_file: .env
    volumes:
      - dbdata:/data/db
volumes:
  dbdata:
  node_modules:
