version: '3'

services:
  ligiappserver:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: liginodejs
    container_name: ligiappserver
    env_file: .env
    ports:
      - '7777:7777'
    volumes:
      - node_modules:/home/node/src/node_modules

  ligiclient:
    build:
      context: ./frontend
    volumes:
      - web-root:/app/build

  ligiwebserver:
    image: nginx:mainline-alpine
    container_name: ligiwebserver
    ports:
      - '80:80'
      - '8080:80'
      - '443:443'
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - ligiclient
      - ligiappserver

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - ligiclient
      - ligiwebserver
    command: certonly --webroot --webroot-path=/var/www/html --email charleswkagiri@gmail.com --agree-tos --no-eff-email --force-renewal -d ligipredictor.com -d www.ligipredictor.com
volumes:
  node_modules:
  web-root:
  certbot-etc:
  certbot-var:
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/ckagiri/predictor/dhparam/
      o: bind
