services:
  api:
    image: ligi-api-devprod
    build:
      dockerfile: ./config/server/prod/Dockerfile
      context: .
      args:
        - APP_ENV=devprod
    volumes:
      - node_modules:/home/node/src/node_modules
    networks:
      - app-network

  client:
    image: ligi-client-devprod
    stdin_open: true
    build:
      dockerfile: ./config/client/prod/Dockerfile
      context: .
      args:
        - APP_ENV=devprod
    ports:
      - '8040:8040'
    networks:
      - app-network

  nginx:
    image: ligi-nginx-devprod
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: ./config/nginx/Dockerfile
      context: .
    ports:
      - '8100:8100'
    networks:
      - app-network

volumes:
  node_modules:

networks:
  app-network:
    driver: bridge
