version: "3"
services:
  ligitestdb:
    image: mongo:4.2-bionic
    container_name: ligitestdb
    env_file: .env.test
    ports:
      - 27000:27017
    volumes:
      - ligitestdbdata:/data/db
volumes:
  ligitestdbdata:
