---
name: Continous Deployment
on:
  push:
    branches:
      - deploy
  workflow_dispatch:
    manual: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create client prod env file
        run: |
          cat <<EOF > config/client/prod/client.env
          NODE_ENV=production
          PORT=8100
          API_URL=http://localhost:8100
          EOF
      - name: Create server prod env file
        run: |
          cat <<EOF > config/server/prod/server.env
          NODE_ENV=production
          PORT=8100
          EOF
      - name: List files in the repository
        run: |
<<<<<<< HEAD
          cat config/client/prod/client.env
          cat config/server/prod/server.env
=======
          ls -a ${{ github.workspace }}
          cat .env
>>>>>>> 73f586268938f811475ef56bbd9d472067c4d684
